### ISSUE TITLE
Incompatibility with newest msquic

### ISSUE THREAD

**Issue by joejnq** [wkgcass/msquic-java#1]
I had a number of issues building the software:

_Running gradle pniGenerate_
I got this error:
Error opening zip file or JAR manifest missing : ../../modify-gradle-compiler-args-agent.jar

So I modified gradle.properties removing the reference to that jar file (which didn' exist)
Then the run succeeded.
<br>
_Running gradle pniCompile_
	I got a bunch of compile errors that mostly reference the same problems.  Here are a couple of examples:

```
In file included from ../c-generated/io_vproxy_msquic_CXPLAT_THREAD_CONFIG.h:14,
                 from io_vproxy_msquic_MsQuic.c:1:
	../c-generated/io_vproxy_msquic_CXPLAT_THREAD_CONFIG.h:21:36: error: unknown type name ‘CXPLAT_THREAD_CONFIG’
   21 | PNIEnvExpand(CXPLAT_THREAD_CONFIG, CXPLAT_THREAD_CONFIG *)

```
or
```
In file included from io_vproxy_msquic_MsQuic.c:4:
../c-generated/io_vproxy_msquic_MsQuicMod.h:22:66: error: unknown type name ‘QUIC_EVENT_LOOP_THREAD_DISPATCH_FN’

```
or

```
22 | JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicModUpcall_dispatch(CXPLAT_THREAD_CONFIG * Config, CXPLAT_EVENTQ * EventQ, void * Thread, void * Context);
|                                                                                  ^~~~~~~~~~~~~~~~~~~~
|                                                                                  PNIBuf_CXPLAT_THREAD_CONFIG
	../c-generated/io_vproxy_msquic_MsQuicModUpcall.h:22:113: error: unknown type name ‘CXPLAT_EVENTQ’
```
My source for msquic was a git pull as of today 4 June 2024.

**Comment by wkgcass** [comment]
## The java agent

You can find `modify-gradle-compiler-args-agent.jar` [here](https://github.com/vproxy-tools/modify-gradle-compiler-args).  
It takes effect when you launch interactive command line programs with Gradle. Gradle creates pipe streams for printing subprocess stdout. When the stream buffer is not full, the stream would flush with a two-second interval, so you will see a huge delay and makes the interactive program nearly unusable.  
The java agent transforms the bytecode, and force it to call `flush()` after each `write()`, so that the stdout could be instantly sent to console.

## The compiling errors

Maybe you are building this project against the official `msquic`?  
There are some small modifications on `msquic`, you might need to use [this version](https://github.com/wkgcass/msquic/blob/modified/README_MODIFIED.md) instead. 

Also I believe you are building this project on Windows?  
Currently windows is not tested yet. But I believe it won't be too hard to pass the compilation, since there aren't too many changes.

**Comment by joejnq** [comment]
Thank you for the fast reply.   I'll try the msquic version  you referenced.  Also, I should have been more complete about my environment.  It's a VM Linux box (Ubuntu).

**Comment by wkgcass** [comment]
The [modified msquic](https://github.com/wkgcass/msquic) is upgraded to 2.4.5 and can compile fine on linux/macos/windows, and already tested on macos.  
I'm closing this issue, feel free to reopen it if needed.
